language: python

python:
  - "2.7"

install:
  - pip install -r dev-requirements.txt

script:
  # Run tests
  - nosetests --with-coverage --cover-package koosli --cover-branches --cover-html

  # Add code coverage to gh-pages
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then ./tools/coverage_to_gh_pages.sh; fi

notifications:
  email: false

env:
  global:

    # GITHUB_TOKEN that grants access to thusoy's account. Used for deploying code coverage to gh-pages branch.
    - secure: "NbnTyOC6d9J3zm6E6ZjI9P3lSCXyfHtlv7r/h8r6K2gyKwOVItixaWhZG1cs9xqKOYJqMibfn8snpWFG1Lg/y0ujYrqoaQZjyQ1ybmVSK1/915/D9pWyJJQZ5NMvENPe1N6w59V/A4SxAYHgYRqM0GbioX87xNYfP2c1D9Vdpd8="
