language: python

python:
  - "2.7"

install:
  - pip install -r dev-requirements.txt

script:
  # Run tests
  - nosetests

  # Add code coverage to gh-pages
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then ./tools/coverage_to_gh_pages.sh; fi

notifications:
  email: false

env:
  global:

    # GITHUB_TOKEN that grants access to thusoy's account. Used for deploying code coverage to gh-pages branch.
    - secure: "cLKqj6oYucS0mt0FT4+lxrTZZrvRf/Ob81RaUqv4NfbMXrtZgTpGoyJBjo/NBOW5Bu4kLjargZvWsoANzIiDBq/usKzuV4GyPouZmksr8aPzUN/VYclOgGxMog99GZ3xe1eS+UWFexeIVD+NB66JRfvOJ+LvgE1iw1537PZLuFI="
