version: 1
formatters:
  simple:
    format: '%(asctime)s %(levelname)-10s %(name)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  koosli:
    level: DEBUG
    handlers: [console]
root:
  level: DEBUG
  handlers: []
disable_existing_loggers: False
